"""
Tool definitions for LLM function calling.
Extracted from original raptor project.
"""

from typing import List, Dict


TOOL_DEFINITIONS = [
    {
        "type": "function",
        "function": {
            "name": "world2mind",
            "description": """Generate cognitive map from the current visual input, transforming it into structured spatial knowledge.

This tool automatically analyzes the video/images that were provided for this session. You do NOT need to specify any file paths — just provide the semantic parameters.

It creates cognitive maps with two types of spatial knowledge:

1. LANDMARK KNOWLEDGE (knowledge_type: "landmark" or "both"):
   - Detected objects with their spatial positions (2D coordinates in meters)
   - Spatial relationships between objects
   - Object attributes (size, area, bounding box)

2. ROUTE KNOWLEDGE (knowledge_type: "route" or "both"):
   - Traversable grid cells (areas where movement is possible)
   - Camera/agent trajectory through the scene
   - Grid-based representation for path planning
   - Requires specifying traversable_categories (ground/surface types like road, sidewalk, floor)

OUTPUT FORMAT for Landmark (output_format parameter):

1. "grid" (For simple tasks):
   - Returns NxN grid cells with object categories per cell
   - Best for: General spatial understanding, "what's in this area", coarse localization
   - Example: Grid_Map: {(0,5): [car], (1,7): [building, tree]}

2. "ellipse" (For fine-grained analysis):
   - Returns ellipse parameters (major/minor axis, rotation angle)
   - Best for: Shape analysis, orientation detection, detailed spatial modeling
   - Example: Ellipse_Axis: (major, minor, angle_degrees)

VISUALIZATIONS:
The tool result includes an `available_visualizations` dict listing generated visualization image paths.
You can use the `view_image` tool to inspect any of these visualizations for deeper spatial understanding.

Use this tool when you need geometric/spatial information that cannot be directly inferred from visual observation alone.""",
            "parameters": {
                "type": "object",
                "properties": {
                    "categories": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "List of object categories to detect as landmarks (e.g., ['car', 'building', 'tree', 'person']). These are objects in the scene."
                    },
                    "scene_type": {
                        "type": "string",
                        "enum": ["indoor", "outdoor"],
                        "description": "Type of scene - affects depth estimation parameters. Default: outdoor"
                    },
                    "knowledge_type": {
                        "type": "string",
                        "enum": ["landmark", "route", "both"],
                        "description": "Type of knowledge to generate: 'landmark' for object positions, 'route' for navigation paths, 'both' for complete cognitive map. Default: both"
                    },
                    "output_format": {
                        "type": "string",
                        "enum": ["rectangle", "ellipse"],
                        "description": "Output format for landmark knowledge: 'rectangle' for bounding boxes (center, width, height), 'ellipse' for ellipse fitting (major/minor axis, angle). Default: rectangle."
                    },
                    "traversable_categories": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "List of ground/surface categories that define traversable areas for route knowledge. Examples: outdoor scenes use ['road', 'sidewalk', 'path', 'grass'], indoor scenes use ['floor', 'carpet', 'tile flooring', 'rug']. Required when knowledge_type is 'route' or 'both'. These will be automatically merged with detection categories."
                    }
                },
                "required": ["categories", "scene_type", "knowledge_type", "output_format"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "view_image",
            "description": """View a visualization image generated by the world2mind tool.

Use this tool to inspect cognitive map visualizations for deeper spatial understanding.
Choose a visualization type from the `available_visualizations` list returned by world2mind.

Available visualization types:
- landmark_vis: 2D cognitive map showing detected objects and their spatial layout
- route_vis: Route knowledge map showing traversable areas and camera trajectory
- pointcloud_rgb_topdown: RGB top-down view of the reconstructed 3D point cloud
- pointcloud_semantic_topdown: Semantic top-down view with color-coded object categories

Call this tool when:
- You need to visually verify object positions or spatial relationships from the map data
- The YAML data alone is insufficient to resolve ambiguity
- You want to cross-check map results against the original visual observation""",
            "parameters": {
                "type": "object",
                "properties": {
                    "visualization_type": {
                        "type": "string",
                        "enum": ["landmark_vis", "route_vis", "pointcloud_rgb_topdown", "pointcloud_semantic_topdown"],
                        "description": "Type of visualization to view (from world2mind's available_visualizations)"
                    }
                },
                "required": ["visualization_type"]
            }
        }
    }
]


def get_tool_definitions() -> List[Dict]:
    """Return tool definitions for OpenAI function calling."""
    return TOOL_DEFINITIONS
